package ec.edu.espe.singleton.view;

import ec.edu.espe.singleton.model.Appointment;
import ec.edu.espe.singleton.utils.AppointmentNotificationService;
import ec.edu.espe.singleton.utils.GUIValidation;
import ec.edu.espe.singleton.utils.MongoManager;
import ec.edu.espe.singleton.model.Date;
import java.text.SimpleDateFormat;

import javax.swing.JOptionPane;

/**
 *
 * @author César Vargas, Paradigm, @ESPE
 */

public class FrmRequestAppointment extends javax.swing.JFrame {

    MongoManager mongoManager = new MongoManager();
    Appointment appointment = new Appointment();
    Date date = new Date();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmRequestAppointment.class.getName());

    /**
     * Creates new form FrmAppointment
     */
    public FrmRequestAppointment() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBackToMenu = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAppointmentId = new javax.swing.JTextField();
        txtPatientId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDoctorId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        calDate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spinMinutes = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        spinHour = new javax.swing.JSpinner();
        btnRequestAppointment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnBackToMenu.setText("Regresar al menú");
        btnBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("CLÍNICA TOAMEDICAL");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("AGENDAR CITA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID de la cita:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("ID del paciente:");

        txtPatientId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientIdActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("ID del doctor:");

        txtDoctorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorIdActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Fecha de la cita:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Hora de la cita");

        jLabel8.setText("Hrs");

        spinMinutes.setModel(new javax.swing.SpinnerNumberModel(0, 0, 55, 5));

        jLabel9.setText("Mins");

        spinHour.setModel(new javax.swing.SpinnerNumberModel(7, 7, 21, 1));

        btnRequestAppointment.setText("Agendar cita");
        btnRequestAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestAppointmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackToMenu)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(224, 224, 224))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(calDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                .addComponent(txtDoctorId, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPatientId, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAppointmentId, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(spinHour, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(spinMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(btnRequestAppointment)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackToMenu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDoctorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtAppointmentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(calDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spinHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(spinMinutes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnRequestAppointment)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestAppointmentActionPerformed
        if (!GUIValidation.validateOnlyNumbers(txtAppointmentId, "id de la cita")) {
            return;
        }
        if (!GUIValidation.validateOnlyNumbers(txtDoctorId, "id del doctor")) {
            return;
        }
        if (!GUIValidation.validateOnlyNumbers(txtPatientId, "id del paciente")) {
            return;
        }
        if (!GUIValidation.validateDateRange(calDate, "Fecha de la cita")) {
            return;
        }

        readValues();

        int option = JOptionPane.showConfirmDialog(rootPane, "Agendando una Cita\n" + appointment, "Confirmar", JOptionPane.YES_NO_CANCEL_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            try {
                int appId = Integer.parseInt(txtAppointmentId.getText());
                int patId = Integer.parseInt(txtPatientId.getText());
                int docId = Integer.parseInt(txtDoctorId.getText());
                java.util.Date selectedDate = calDate.getDate();
                int hour = (Integer) spinHour.getValue();
                int minute = (Integer) spinMinutes.getValue();

                if (checkIdExists(appId)) {
                    JOptionPane.showMessageDialog(rootPane, "Error: El ID de cita " + appId + " ya existe.", "ID Duplicado", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (!checkPatientExists(patId)) {
                    JOptionPane.showMessageDialog(rootPane, "Error: El paciente con ID " + patId + " no existe.", "Paciente No Encontrado", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (!checkDoctorExists(docId)) {
                    JOptionPane.showMessageDialog(rootPane, "Error: El doctor con ID " + docId + " no existe.", "Doctor No Encontrado", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (checkScheduleConflict(docId, selectedDate, hour, minute)) {
                    JOptionPane.showMessageDialog(rootPane, "El doctor ya tiene una cita en ese horario.", "Horario Ocupado", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                org.bson.Document dateObject = mongoManager.createDateDocument(selectedDate, hour, minute);

                org.bson.Document appointmentDoc = new org.bson.Document();
                appointmentDoc.append("appointmentId", appId);
                appointmentDoc.append("patientId", patId);
                appointmentDoc.append("doctorId", docId);
                appointmentDoc.append("status", "Agendado");
                appointmentDoc.append("date", dateObject);

                mongoManager.insert("appointments", appointmentDoc);
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                String dateString = sdf.format(selectedDate) + " a las " + hour + ":" + (minute < 10 ? "0" + minute : minute);
                sendNotificationInBackground(String.valueOf(patId), dateString);

                JOptionPane.showMessageDialog(rootPane, "La cita fue guardada exitosamente.");
                emptyFields();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnRequestAppointmentActionPerformed

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed

    }//GEN-LAST:event_btnBackToMenuActionPerformed

    private void txtPatientIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientIdActionPerformed

    private void txtDoctorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorIdActionPerformed

    private void emptyFields() {

        txtAppointmentId.setText("");
        txtPatientId.setText("");
        txtDoctorId.setText("");
        calDate.setDate(null);
        spinHour.setValue(7);
        spinMinutes.setValue(0);
    }

    private void readValues() {

        int appoinmentId = Integer.parseInt(txtAppointmentId.getText());
        int patientId = Integer.parseInt(txtPatientId.getText());
        int doctorId = Integer.parseInt(txtDoctorId.getText());
        java.util.Date dateSelected = calDate.getDate();

        SimpleDateFormat yearFormat = new SimpleDateFormat("yyyy");
        SimpleDateFormat monthFormat = new SimpleDateFormat("MM");
        SimpleDateFormat dayFormat = new SimpleDateFormat("dd");

        int year = Integer.parseInt(yearFormat.format(dateSelected));
        int month = Integer.parseInt(monthFormat.format(dateSelected));
        int day = Integer.parseInt(dayFormat.format(dateSelected));

        int hour = Integer.valueOf(spinHour.getValue().toString());
        int minute = Integer.valueOf(spinMinutes.getValue().toString());

        date = new Date(day, month, year, hour, minute);

        appointment = new Appointment(appoinmentId, date, patientId, doctorId);
    }

    private boolean checkIdExists(int id) {
        org.bson.Document filter = new org.bson.Document("appointmentId", id);
        java.util.List<org.bson.Document> results = mongoManager.find("appointments", filter);
        return !results.isEmpty();
    }

    private boolean checkDoctorExists(int doctorId) {
        org.bson.Document filter = new org.bson.Document("doctorId", doctorId);
        java.util.List<org.bson.Document> results = mongoManager.find("doctors", filter);
        return !results.isEmpty();
    }

    private boolean checkScheduleConflict(int doctorId, java.util.Date date, int hour, int minute) {
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String dateString = sdf.format(date);
        String timeString = String.format("%02d:%02d", hour, minute);

        org.bson.Document filter = new org.bson.Document("doctorId", doctorId)
                .append("date.date", dateString)
                .append("date.time", timeString);

        java.util.List<org.bson.Document> results = mongoManager.find("appointments", filter);
        return !results.isEmpty();
    }

    private boolean checkPatientExists(int patientId) {
        org.bson.Document filter = new org.bson.Document("patientId", patientId);
        java.util.List<org.bson.Document> results = mongoManager.find("patients", filter);
        return !results.isEmpty();
    }

private void sendNotificationInBackground(String patientId, String dateInfo) {
        new Thread(() -> {
            try {
                int patientIdInt = Integer.parseInt(patientId);

                String patientEmail = mongoManager.getEmail("patients", "patientId", patientIdInt);

                AppointmentNotificationService service = new AppointmentNotificationService();
                
                String patientName = mongoManager.getInfo("patients", "patientId", patientIdInt, "fullName");
                service.sendReservationConfirmation(patientEmail, patientName, dateInfo);

            } catch (Exception e) {
                System.err.println("Error enviando notificación: " + e.getMessage());
            }
        }).start();
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmRequestAppointment().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnRequestAppointment;
    private com.toedter.calendar.JDateChooser calDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spinHour;
    private javax.swing.JSpinner spinMinutes;
    private javax.swing.JTextField txtAppointmentId;
    private javax.swing.JTextField txtDoctorId;
    private javax.swing.JTextField txtPatientId;
    // End of variables declaration//GEN-END:variables
}
