
package ec.edu.espe.clinicmanagementsystem.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Adrian Toapanta, Object Masters, @ESPE
 */
public class FrmCreatePrescription extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCreatePrescription.class.getName());

    /**
     * Creates new form CreatePrescription
     */
    public FrmCreatePrescription() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrescriptionNameLb = new javax.swing.JPanel();
        cedulaLb = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        MedicamentoLb = new javax.swing.JLabel();
        txtMedication = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBoxobservaciones = new javax.swing.JTextArea();
        SaveButton = new javax.swing.JButton();
        PrescriptionLb = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnBackToMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PrescriptionNameLb.setBackground(new java.awt.Color(255, 255, 255));

        cedulaLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cedulaLb.setText("Cédula del paciente: ");

        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });

        MedicamentoLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MedicamentoLb.setText("Nombre del medicamento:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Indicaciones médicas:");

        txtBoxobservaciones.setColumns(20);
        txtBoxobservaciones.setRows(5);
        jScrollPane1.setViewportView(txtBoxobservaciones);

        SaveButton.setText("Guardar");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        PrescriptionLb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PrescriptionLb.setText("CREAR PRESCRIPCIÓN");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("CLÍNICA TOAMEDICAL");

        btnBackToMenu.setText("Regresar al menú");
        btnBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PrescriptionNameLbLayout = new javax.swing.GroupLayout(PrescriptionNameLb);
        PrescriptionNameLb.setLayout(PrescriptionNameLbLayout);
        PrescriptionNameLbLayout.setHorizontalGroup(
            PrescriptionNameLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrescriptionNameLbLayout.createSequentialGroup()
                .addGroup(PrescriptionNameLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrescriptionNameLbLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(PrescriptionNameLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cedulaLb, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MedicamentoLb, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(PrescriptionNameLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMedication, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PrescriptionNameLbLayout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(PrescriptionLb))
                    .addGroup(PrescriptionNameLbLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackToMenu)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel10))
                    .addGroup(PrescriptionNameLbLayout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(SaveButton)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        PrescriptionNameLbLayout.setVerticalGroup(
            PrescriptionNameLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrescriptionNameLbLayout.createSequentialGroup()
                .addGroup(PrescriptionNameLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrescriptionNameLbLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel10))
                    .addGroup(PrescriptionNameLbLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackToMenu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PrescriptionLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(PrescriptionNameLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cedulaLb)
                    .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(PrescriptionNameLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedicamentoLb)
                    .addComponent(txtMedication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(PrescriptionNameLbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(SaveButton)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PrescriptionNameLb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrescriptionNameLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        JOptionPane.showMessageDialog(rootPane,"Preescripcion Creada");
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
        FrmDoctorMenu login = new FrmDoctorMenu();
        login.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCreatePrescription().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MedicamentoLb;
    private javax.swing.JLabel PrescriptionLb;
    private javax.swing.JPanel PrescriptionNameLb;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JTextField cedula;
    private javax.swing.JLabel cedulaLb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtBoxobservaciones;
    private javax.swing.JTextField txtMedication;
    // End of variables declaration//GEN-END:variables
}
