package ec.edu.espe.clinicmanagementsystem.view;

import ec.edu.espe.clinicmanagementsystem.utils.GUIValidation;
import ec.edu.espe.clinicmanagementsystem.utils.MongoManager;
import javax.swing.JOptionPane;

/**
 *
 * @author César Vargas, Paradigm, @ESPE
 */
public class FrmModifyReceptionist extends javax.swing.JFrame {

    MongoManager mongoManager = new MongoManager();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmModifyReceptionist.class.getName());

    /**
     * Creates new form FrmModifyReceptionist
     */
    public FrmModifyReceptionist() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtReceptionistId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtpRecepcionistFound = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNewPhone = new javax.swing.JTextField();
        txtNewEmail = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtpOldPhone = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtpOldEmail = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        btnBackToMenu = new javax.swing.JButton();
        btnUpdateData = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("ID del recepcionista: ");

        txtReceptionistId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReceptionistIdActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Recepcionista encontrado:");

        jScrollPane1.setViewportView(txtpRecepcionistFound);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Deje el campo en blanco si no desea actualizar el dato:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Nuevo Teléfono: ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nuevo Email:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Teléfono previo registrado:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Email previo registrado:");

        jScrollPane2.setViewportView(txtpOldPhone);

        jScrollPane3.setViewportView(txtpOldEmail);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ACTUALIZAR DATOS RECEPCIONISTA");

        btnBackToMenu.setText("Regresar al menú");
        btnBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuActionPerformed(evt);
            }
        });

        btnUpdateData.setText("Actualizar Datos");
        btnUpdateData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDataActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("CLÍNICA TOAMEDICAL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(btnUpdateData))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackToMenu)
                        .addGap(227, 227, 227)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtReceptionistId, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(86, 86, 86)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNewPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(txtNewEmail))))))
                .addGap(0, 46, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnBackToMenu)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(48, 48, 48)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtReceptionistId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNewPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnUpdateData)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDataActionPerformed
        if (!ec.edu.espe.clinicmanagementsystem.utils.GUIValidation.validateOnlyNumbers(txtReceptionistId, "id del Recepcionista")) {
            return;
        }

        searchReceptionist();
        if (txtpRecepcionistFound.getText().isEmpty()) {
            return;
        }

        int option = javax.swing.JOptionPane.showConfirmDialog(rootPane, "¿Está seguro de actualizar los datos?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);

        if (option == javax.swing.JOptionPane.YES_OPTION) {
            try {
                int id = Integer.parseInt(txtReceptionistId.getText());
                org.bson.Document filter = new org.bson.Document("receptionistId", id);
                org.bson.Document updateData = new org.bson.Document();

                boolean existChanges = false;

                if (!txtNewPhone.getText().isEmpty()) {
                    if (!ec.edu.espe.clinicmanagementsystem.utils.GUIValidation.validateNumericLength(txtNewPhone, "Nuevo Teléfono", 10)) {
                        return;
                    }
                    updateData.append("phone", txtNewPhone.getText());
                    existChanges = true;
                }

                if (!txtNewEmail.getText().isEmpty()) {
                    if (!ec.edu.espe.clinicmanagementsystem.utils.GUIValidation.validateEmail(txtNewEmail, "Nuevo Email")) {
                        return;
                    }
                    updateData.append("email", txtNewEmail.getText());
                    existChanges = true;
                }

                if (existChanges) {
                    long count = mongoManager.update("receptionists", filter, updateData);

                    if (count > 0) {
                        javax.swing.JOptionPane.showMessageDialog(rootPane, "Datos actualizados exitosamente.");
                        emptyFields();
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(rootPane, "No se pudo actualizar.");
                    }
                } else {
                    javax.swing.JOptionPane.showMessageDialog(rootPane, "No ingresó datos nuevos para actualizar.");
                }

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(rootPane, "Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnUpdateDataActionPerformed
    private void searchReceptionist() {
        if (txtReceptionistId.getText().isEmpty()) {
            return;
        }

        try {
            int id = Integer.parseInt(txtReceptionistId.getText());
            org.bson.Document filter = new org.bson.Document("receptionistId", id);

            java.util.List<org.bson.Document> results = mongoManager.find("receptionists", filter);

            if (!results.isEmpty()) {
                org.bson.Document doc = results.get(0);
                txtpRecepcionistFound.setText(doc.getString("name"));
                txtpOldPhone.setText(doc.getString("phone"));
                txtpOldEmail.setText(doc.getString("email"));
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Recepcionista no encontrado.");
                txtpRecepcionistFound.setText("");
                txtpOldPhone.setText("");
                txtpOldEmail.setText("");
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El ID debe ser numérico.");
        }
    }
    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
        FrmReceptionistMenu login = new FrmReceptionistMenu();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    private void txtReceptionistIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReceptionistIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReceptionistIdActionPerformed

    private void emptyFields() {
        txtReceptionistId.setText("");
        txtpRecepcionistFound.setText("");
        txtNewPhone.setText("");
        txtNewEmail.setText("");
        txtpOldEmail.setText("");
        txtpOldPhone.setText("");
    }

    private void readValues() {

        int receptionistId = Integer.parseInt(txtReceptionistId.getText());
        String newPhone = txtNewPhone.getText();
        String newEmail = txtNewEmail.getText();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmModifyReceptionist().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnUpdateData;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtNewEmail;
    private javax.swing.JTextField txtNewPhone;
    private javax.swing.JTextField txtReceptionistId;
    private javax.swing.JTextPane txtpOldEmail;
    private javax.swing.JTextPane txtpOldPhone;
    private javax.swing.JTextPane txtpRecepcionistFound;
    // End of variables declaration//GEN-END:variables
}
