/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.clinicmanagementsystem.view;

/**
 *
 * @author Windows
 */
public class FrmDoctorMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmDoctorMenu.class.getName());

    /**
     * Creates new form DoctorMenu
     */
    public FrmDoctorMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnShowMedicalHistory = new javax.swing.JButton();
        btnGenerateBilling = new javax.swing.JButton();
        btnShowDoctorAppointment = new javax.swing.JButton();
        btnAddMedicalHistory = new javax.swing.JButton();
        btnAddPrescription = new javax.swing.JButton();
        btnModifyMedicalHistory = new javax.swing.JButton();
        btnCheckAppointment = new javax.swing.JButton();
        btnSignOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Menú de doctor.");

        btnShowMedicalHistory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnShowMedicalHistory.setText("Ver historia clínica de paciente.");
        btnShowMedicalHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowMedicalHistoryActionPerformed(evt);
            }
        });

        btnGenerateBilling.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGenerateBilling.setText("Generar factura.");
        btnGenerateBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateBillingActionPerformed(evt);
            }
        });

        btnShowDoctorAppointment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnShowDoctorAppointment.setText("Ver mis citas");

        btnAddMedicalHistory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddMedicalHistory.setText("Añadir registro a historia clínica.");
        btnAddMedicalHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMedicalHistoryActionPerformed(evt);
            }
        });

        btnAddPrescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddPrescription.setText("Crear prescripción.");
        btnAddPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPrescriptionActionPerformed(evt);
            }
        });

        btnModifyMedicalHistory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnModifyMedicalHistory.setText("Modificar registro de historia clínica.");
        btnModifyMedicalHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyMedicalHistoryActionPerformed(evt);
            }
        });

        btnCheckAppointment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCheckAppointment.setText("Marcar cita como completada");

        btnSignOut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSignOut.setText("Cerrar sesión");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSignOut)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerateBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAddMedicalHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnShowMedicalHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(btnShowDoctorAppointment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAddPrescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModifyMedicalHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCheckAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSignOut)
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModifyMedicalHistory)
                    .addComponent(btnAddMedicalHistory))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowMedicalHistory)
                    .addComponent(btnAddPrescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCheckAppointment)
                    .addComponent(btnShowDoctorAppointment, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGenerateBilling)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowMedicalHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowMedicalHistoryActionPerformed
        FrmViewMedicalHistory login = new FrmViewMedicalHistory ();
        login.setVisible(true);


        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowMedicalHistoryActionPerformed

    private void btnGenerateBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateBillingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerateBillingActionPerformed

    private void btnModifyMedicalHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyMedicalHistoryActionPerformed
        FrmModifyMedicalRecord login = new FrmModifyMedicalRecord ();
        login.setVisible(true);


        this.dispose();
    }//GEN-LAST:event_btnModifyMedicalHistoryActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        FrmLogInDoctor login = new FrmLogInDoctor ();
        login.setVisible(true);


        this.dispose();
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnAddMedicalHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMedicalHistoryActionPerformed
        FrmAddNewMedicalRecord login = new FrmAddNewMedicalRecord ();
        login.setVisible(true);


        this.dispose();
    }//GEN-LAST:event_btnAddMedicalHistoryActionPerformed

    private void btnAddPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPrescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddPrescriptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmDoctorMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMedicalHistory;
    private javax.swing.JButton btnAddPrescription;
    private javax.swing.JButton btnCheckAppointment;
    private javax.swing.JButton btnGenerateBilling;
    private javax.swing.JButton btnModifyMedicalHistory;
    private javax.swing.JButton btnShowDoctorAppointment;
    private javax.swing.JButton btnShowMedicalHistory;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
