/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.clinicmanagementsystem.view;

/**
 *
 * @author Thais Santórum
 */
public class FrmDoctorMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmDoctorMenu.class.getName());

    /**
     * Creates new form DoctorMenu
     */
    public FrmDoctorMenu() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itmSignOut = new javax.swing.JMenuItem();
        itmExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itmAddNewMedicalRecord = new javax.swing.JMenuItem();
        itmModifyMedicalRecord = new javax.swing.JMenuItem();
        timViewMedicalRecord = new javax.swing.JMenuItem();
        itmViewPrescription = new javax.swing.JMenuItem();
        itmViewAppointments = new javax.swing.JMenuItem();
        itmCheckAppointment = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Menú de doctor.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel1)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        jMenu1.setText("Usuario");

        itmSignOut.setText("Cerrar sesión");
        itmSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSignOutActionPerformed(evt);
            }
        });
        jMenu1.add(itmSignOut);

        itmExit.setText("Salir");
        itmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExitActionPerformed(evt);
            }
        });
        jMenu1.add(itmExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opciones");

        itmAddNewMedicalRecord.setText("Añadir registro a historia clínica");
        itmAddNewMedicalRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAddNewMedicalRecordActionPerformed(evt);
            }
        });
        jMenu2.add(itmAddNewMedicalRecord);

        itmModifyMedicalRecord.setText("Modificar registro de historia clínica");
        itmModifyMedicalRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmModifyMedicalRecordActionPerformed(evt);
            }
        });
        jMenu2.add(itmModifyMedicalRecord);

        timViewMedicalRecord.setText("Ver historia clínica del paciente");
        timViewMedicalRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timViewMedicalRecordActionPerformed(evt);
            }
        });
        jMenu2.add(timViewMedicalRecord);

        itmViewPrescription.setText("Crear prescripción");
        itmViewPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmViewPrescriptionActionPerformed(evt);
            }
        });
        jMenu2.add(itmViewPrescription);

        itmViewAppointments.setText("Ver mis citas");
        itmViewAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmViewAppointmentsActionPerformed(evt);
            }
        });
        jMenu2.add(itmViewAppointments);

        itmCheckAppointment.setText("Marcar cita como completada");
        itmCheckAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCheckAppointmentActionPerformed(evt);
            }
        });
        jMenu2.add(itmCheckAppointment);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSignOutActionPerformed
        FrmLogInDoctor login = new FrmLogInDoctor ();
        login.setVisible(true);


        this.dispose();
    }//GEN-LAST:event_itmSignOutActionPerformed

    private void itmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExitActionPerformed
         System.exit(0);

    }//GEN-LAST:event_itmExitActionPerformed

    private void itmAddNewMedicalRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAddNewMedicalRecordActionPerformed
        FrmAddNewMedicalRecord login = new FrmAddNewMedicalRecord ();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itmAddNewMedicalRecordActionPerformed

    private void itmModifyMedicalRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmModifyMedicalRecordActionPerformed
        FrmModifyMedicalRecord login = new FrmModifyMedicalRecord ();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itmModifyMedicalRecordActionPerformed

    private void itmCheckAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCheckAppointmentActionPerformed
        FrmCheckAppointment login = new FrmCheckAppointment ();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itmCheckAppointmentActionPerformed

    private void itmViewAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmViewAppointmentsActionPerformed
        FrmViewAppointments view = new FrmViewAppointments ();
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itmViewAppointmentsActionPerformed

    private void itmViewPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmViewPrescriptionActionPerformed
        FrmCreatePrescription view = new FrmCreatePrescription ();
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itmViewPrescriptionActionPerformed

    private void timViewMedicalRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timViewMedicalRecordActionPerformed
        FrmViewMedicalHistoryDoctor login = new FrmViewMedicalHistoryDoctor ();
        login.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_timViewMedicalRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmDoctorMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAddNewMedicalRecord;
    private javax.swing.JMenuItem itmCheckAppointment;
    private javax.swing.JMenuItem itmExit;
    private javax.swing.JMenuItem itmModifyMedicalRecord;
    private javax.swing.JMenuItem itmSignOut;
    private javax.swing.JMenuItem itmViewAppointments;
    private javax.swing.JMenuItem itmViewPrescription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem timViewMedicalRecord;
    // End of variables declaration//GEN-END:variables
}
