package ec.edu.espe.clinicmanagementsystem.view;

import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import ec.edu.espe.clinicmanagementsystem.utils.MongoManager;
import java.util.List;
import org.bson.Document;

/**
 *
 * @author César Vargas, Paradigm, @ESPE
 */
public class FrmViewMedicalHistoryDoctor extends javax.swing.JFrame {
   private MongoManager mongoManager;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmViewMedicalHistoryDoctor.class.getName());

    /**
     * Creates new form FrmViewMedicalHistory
     */
    public FrmViewMedicalHistoryDoctor() {
        initComponents();
        txtMedicalHistory.setEditable(false);
        this.mongoManager = new MongoManager();
        this.setLocationRelativeTo(null);
       cargarHistoriasClinicas();
    }
   private void cargarHistoriasClinicas() {

        List<Document> historiales = mongoManager.getAll("medicalHistorys");
        
        for (Document doc : historiales) {
            System.out.println(doc.toJson());
        }
    }
   private void cerrarFormulario() {
        mongoManager.close();
        this.dispose();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPatientId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtpPatientFound = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMedicalHistory = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBackToMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("ID del Paciente:");

        txtPatientId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientIdActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Historial médico para:");

        jScrollPane1.setViewportView(txtpPatientFound);

        txtMedicalHistory.setColumns(20);
        txtMedicalHistory.setRows(5);
        jScrollPane2.setViewportView(txtMedicalHistory);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("VER HISTORIA MEDICA DEL PACIENTE");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("CLINICA TOAMEDICAL");

        btnBackToMenu.setText("Regresar al menú");
        btnBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnBackToMenu)
                        .addGap(279, 279, 279)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2))
                            .addComponent(jLabel1))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBackToMenu)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
        FrmDoctorMenu login = new FrmDoctorMenu();
        login.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    private void txtPatientIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientIdActionPerformed
String idIngresado = txtPatientId.getText().trim();

        if (idIngresado.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID de paciente.");
            return;
        }

        try {
            // Intentamos convertir el ID a número
            int idABuscar = Integer.parseInt(idIngresado);
            
            // Filtro para buscar por patientId
            Document filtro = new Document("patientId", idABuscar);
            
            // Usamos el manager para buscar en la colección "medicalHistorys"
            List<Document> resultados = mongoManager.find("medicalHistorys", filtro);
            
            // Obtenemos el primer resultado de la lista (si existe)
            Document resultado = resultados.isEmpty() ? null : resultados.get(0);

            if (resultado != null) {
                StringBuilder sb = new StringBuilder();
                sb.append("=========================================\n");
                sb.append("    HISTORIAL CLÍNICO - MODO DOCTOR      \n");
                sb.append("=========================================\n\n");
                
                sb.append("ID Registro:  ").append(resultado.getOrDefault("historyId", "N/A")).append("\n");
                
                // Usamos el formateador de fecha de tu MongoManager
                String fechaLimpia = mongoManager.dateFormated(resultado.get("date"), false);
                sb.append("Fecha:        ").append(fechaLimpia).append("\n");
                
                // Usamos getOrDefault para evitar errores si el campo está vacío en la base
                sb.append("Alergias:     ").append(resultado.getOrDefault("allergies", "Ninguna")).append("\n");
                sb.append("Enfermedades: ").append(resultado.getOrDefault("diseases", "Ninguna")).append("\n");
                sb.append("Tratamientos: ").append(resultado.getOrDefault("treatments", "Ninguno")).append("\n");
                sb.append("-----------------------------------------\n");
                sb.append("Observaciones del Médico:\n").append(resultado.getOrDefault("observations", "Sin observaciones")).append("\n");
                sb.append("=========================================\n");

                // Mostramos la información en el JTextArea
                txtMedicalHistory.setText(sb.toString());
                txtMedicalHistory.setCaretPosition(0); 
                
                // Actualizamos el panel de información superior
                txtpPatientFound.setText("Resultados para el Paciente ID: " + idABuscar);
                
            } else {
                emptyFields();
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontró historial para el paciente con ID: " + idABuscar);
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "El ID debe ser un número entero válido.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al procesar la búsqueda: " + e.getMessage());
        }
    }//GEN-LAST:event_txtPatientIdActionPerformed

    private void emptyFields() {
        
        txtPatientId.setText("");
        txtpPatientFound.setText("");
        txtMedicalHistory.setText(""); 
    }
    
    
    private void readValues() {
        
        int patientId = Integer.parseInt(txtPatientId.getText());        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmViewMedicalHistoryDoctor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtMedicalHistory;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextPane txtpPatientFound;
    // End of variables declaration//GEN-END:variables
}
